// Troque 'transactions' pelo nome que aparecer no seu Supabase
const { data } = await supabase.from('nome_da_sua_tabela').select('*')...

// E aqui também no salvamento:
const { error } = await supabase.from('nome_da_sua_tabela').insert([{...